[profile.default]
solc = "0.8.19"
src = "src"
test = "test"
script = "script"
out = "out"
optimizer_runs = 1_000_000
block_timestamp = 1681776964 # unix time - whatever time I set this up randomly
fuzz = { runs = 1_000 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
goerli = { key = "${API_KEY_ETHERSCAN}" }


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
localhost = "http://localhost:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
